[package]
name = "feeder"
version = "0.1.0"
authors = ["Arran France <arran@arranfrance.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
actix = "0.7"
actix-web = { version="0.7", features=["alpn"] }
futures = "0.1"
openssl-probe = "0.1.2"